import type { Task } from '@/types'

export const SEED_TASKS: Task[] = [
  { id: 1,  phase: 1, icon: '📋', title: 'Document every task Rhiannon does in a week',          description: 'Time audit. No mercy. Every email, every reconciliation, every client question. This is the map of what needs to be delegated.',                                                                                       xp: 50,  impact_label: 'HIGH IMPACT' },
  { id: 2,  phase: 1, icon: '🎯', title: 'Identify the 20% eating 80% of her time',              description: 'Find the 3–5 repeatable tasks that show up every week. These become your first delegation targets.',                                                                                                                   xp: 40,  impact_label: '' },
  { id: 3,  phase: 1, icon: '🤝', title: 'Hire or assign a junior bookkeeper / controller support', description: 'One hire or contractor removes 60% of the day-to-day. Entry-level, trained to Thryve\'s standards. This is the unlock.',                                                                                            xp: 100, impact_label: 'CRITICAL HIRE' },
  { id: 4,  phase: 1, icon: '📝', title: 'Write one SOP for the most repeated task',              description: 'Doesn\'t have to be perfect. A Loom + a Google Doc is enough. The discipline of documenting teaches what\'s actually complex vs. routine.',                                                                           xp: 30,  impact_label: '' },
  { id: 5,  phase: 1, icon: '📅', title: 'Block 4 hours/week as Leadership Time — non-negotiable', description: 'Put it in the calendar. Treat it like a client meeting. Use it for strategy, team building, reading, thinking. It looks empty. It isn\'t.',                                                                           xp: 25,  impact_label: '' },
  { id: 6,  phase: 2, icon: '🗂️', title: 'Build a repeatable month-end close checklist',          description: 'The close is the most time-intensive monthly cycle. Systematize it so a junior can execute with Rhiannon reviewing — not doing.',                                                                                      xp: 60,  impact_label: '' },
  { id: 7,  phase: 2, icon: '👥', title: 'Set up a weekly team standup (15 min, not a meeting)',  description: 'Problems surface faster. Blockers get cleared. Rhiannon gets information without being the bottleneck.',                                                                                                               xp: 35,  impact_label: '' },
  { id: 8,  phase: 2, icon: '💼', title: 'Define Thryve\'s service tiers and delivery standards in writing', description: 'What does a Thryve engagement actually look like at each level? Written standards mean anyone can deliver to spec — not just Rhiannon.',                                                                 xp: 50,  impact_label: 'HIGH IMPACT' },
  { id: 9,  phase: 2, icon: '🧭', title: 'Rhiannon does one leadership-only client QBR',          description: 'No prep work, no data entry. Just the strategic conversation. She shows up as a trusted advisor, not a bookkeeper.',                                                                                                   xp: 45,  impact_label: '' },
  { id: 10, phase: 2, icon: '📊', title: 'Create a simple internal scorecard (weekly, 1 page)',   description: 'Revenue, pipeline, client health, capacity. Rhiannon reviews it. Doesn\'t build it.',                                                                                                                                 xp: 40,  impact_label: '' },
  { id: 11, phase: 3, icon: '🏗️', title: 'Hire or promote a senior accountant / controller',     description: 'This person owns delivery quality. Rhiannon sets the bar; they maintain it. This is the hire that actually frees her from the work for good.',                                                                         xp: 100, impact_label: 'CRITICAL HIRE' },
  { id: 12, phase: 3, icon: '🎤', title: 'Rhiannon speaks or appears publicly once',              description: 'One strong LinkedIn post, one podcast episode, one panel talk. She is the face of Thryve\'s expertise. This opens doors that cold calls don\'t.',                                                                       xp: 55,  impact_label: '' },
  { id: 13, phase: 3, icon: '🤝', title: 'Build one strategic referral partnership',              description: 'One banker, one insurance broker, one M&A advisor, one business attorney. One relationship done right is worth more than 50 LinkedIn connections.',                                                                    xp: 65,  impact_label: '' },
  { id: 14, phase: 3, icon: '📈', title: 'Define the $5M plan on paper (revenue, headcount, services)', description: 'At $5M ARR, what does Thryve look like? How many clients? How many staff? What does Rhiannon\'s week look like? Write it down. Make it real.',                                                                xp: 50,  impact_label: '' },
  { id: 15, phase: 3, icon: '💡', title: 'Lead one internal quarterly planning session',           description: 'Not a bookkeeping session. A business planning session. Where are we? Where are we going? What do we fix next quarter? Rhiannon runs it.',                                                                             xp: 45,  impact_label: '' },
  { id: 16, phase: 4, icon: '🗓️', title: 'Calendar audit — zero execution tasks remain',         description: 'Look at the calendar. Every recurring task that belongs to a junior or a system gets moved. If she\'s still touching client deliverables directly, something hasn\'t transferred yet.',                                 xp: 60,  impact_label: '' },
  { id: 17, phase: 4, icon: '🏆', title: 'Conduct annual performance reviews for the whole team', description: 'Who\'s a keeper? Who needs development? Where are the gaps heading into year two? This is her first formal moment as a people leader.',                                                                                 xp: 50,  impact_label: '' },
  { id: 18, phase: 4, icon: '🌐', title: 'Close one deal that came from her network or positioning', description: 'Not from cold outreach. From her reputation. A referral, a speaking engagement, a LinkedIn post. Proof that she\'s a rainmaker, not just an operator.',                                                             xp: 80,  impact_label: 'MILESTONE' },
  { id: 19, phase: 4, icon: '📜', title: 'Write a one-page Thryve Way culture doc',               description: 'How do we operate? What do we believe about clients? What\'s not acceptable? This is the DNA of the company. Leaders write this. Employees live it.',                                                                    xp: 40,  impact_label: '' },
  { id: 20, phase: 4, icon: '👑', title: 'Present a Year 2 growth roadmap to Nic and the team',  description: 'Where is Thryve in 12 months? New markets? New hires? New services? This is the moment she leads from the front. Not the bookkeeper. The architect.',                                                                   xp: 100, impact_label: 'FINAL BOSS' },
]

export const PHASE_META = [
  { phase: 1, name: 'Build the Foundation', tagline: 'Hire what she does. Free what she is.', months: 'Months 1–3' },
  { phase: 2, name: 'Build the Systems',    tagline: 'Thryve runs the work. Rhiannon runs Thryve.', months: 'Months 4–6' },
  { phase: 3, name: 'Build the Growth Engine', tagline: "She's not the product. She's the standard.", months: 'Months 7–9' },
  { phase: 4, name: 'Lead the Company',     tagline: 'Full-time CEO. No asterisk.', months: 'Months 10–12' },
]
